services:
  # Backend API Service
  - type: web
    name: caregiver-chatbot-backend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    buildCommand: docker build -t backend ./backend
    startCommand: docker run -p $PORT:8000 backend
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

  # Frontend Web Service
  - type: web
    name: caregiver-chatbot-frontend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /
    buildCommand: docker build -t frontend ./caregiver-chatbot
    startCommand: docker run -p $PORT:80 frontend
    dockerfilePath: ./caregiver-chatbot/Dockerfile
    dockerContext: ./caregiver-chatbot
    envVars:
      - key: REACT_APP_API_URL
        value: https://caregiver-chatbot-backend.onrender.com 