services:
  # Backend API Service
  - type: web
    name: caregiver-chatbot-backend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

  # Frontend Web Service
  - type: web
    name: caregiver-chatbot-frontend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /
    dockerfilePath: ./caregiver-chatbot/Dockerfile
    dockerContext: ./caregiver-chatbot
    envVars:
      - key: REACT_APP_API_URL
        value: https://caregiver-chatbot-backend.onrender.com 