services:
  # Backend API Service
  - type: web
    name: caregiver-chatbot-backend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    buildCommand: cd backend && docker build -t backend .
    startCommand: docker run -p $PORT:8000 backend

  # Frontend Web Service
  - type: web
    name: caregiver-chatbot-frontend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /
    buildCommand: cd caregiver-chatbot && docker build -t frontend .
    startCommand: docker run -p $PORT:80 frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://caregiver-chatbot-backend.onrender.com 